# Generated by Django 3.1.7 on 2021-04-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210411_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='categoty',
            field=models.ManyToManyField(to='blog.Category', verbose_name='دسته بندی'),
        ),
    ]
